// @ts-nocheck
import {
  ThirdwebSDKProvider,
  metamaskWallet,
  coinbaseWallet,
  walletConnect,
} from "@thirdweb-dev/react";
import { CHAIN } from "../const/chains";
import { Inter } from "next/font/google";
import { Nav } from "../components/Navbar";
import Channel from "../components/ui/Channel"
import { LocalWallet } from "@thirdweb-dev/wallets";
import { Goerli } from "@thirdweb-dev/chains";
import { Signer } from "ethers";

import Button from "../components/demo/WalletConnection"
import React, {useState, useEffect} from 'react'
import Head from "next/head";
import "../styles/globals.css";
import type { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

function MyApp({ Component, pageProps }: AppProps) {
  const [signer, setSigner] = useState<Signer | null>(null);

  // in this example we just generate a random wallet
  useEffect(() => {
    const generateWallet = async () => {
      const localWallet = new LocalWallet({
        chain: Goerli,
      });
      localWallet.generate();
      localWallet.connect();
      setSigner(await localWallet.getSigner());
    };
    generateWallet();
  }, []);

  return (
    <div className={inter.className}>
      <Head>
        <title>EVM Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThirdwebSDKProvider
          activeChain={Goerli}
          signer={signer}
          clientId="your-client-id"
        >
          <Nav />
          <Button />
          <Channel signer={signer} />
          {/* <Component {...pageProps} /> */}
        </ThirdwebSDKProvider>
      </main>
    </div>
  );
}

export default MyApp;
